version: '3'
services:
  app:
    build: .
    container_name: angularapp
    volumes:
    - ${PWD}:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    ports:
    - "4200:4200"
